# Generated by Django 5.2.3 on 2025-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('book_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Físico')], max_length=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
