# Generated by Django 5.2.5 on 2025-12-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('fisico', 'Físico')], max_length=10),
        ),
    ]
