# Generated by Django 5.2.5 on 2025-12-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_cover_image_alter_book_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
